使用pip3 出现以下错误：

Traceback (most recent call last): 
File “/usr/bin/pip3”, line 9, in 
from pip import main
解决办法

修改 /usr/bin/pip 文件

from pip import main
if __name__ == '__main__':
    sys.exit(main())

改为：

from pip import __main__
if __name__ == '__main__':
    sys.exit(__main__._main())

Traceback (most recent call last):
  File "/usr/bin/pip3", line 11, in 
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.5/locale.py", line 594, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

解决方法：

在 Linux 终端输入以下命令，即可

export LC_ALL=C

